security:

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$AdA1Oh3.Ra70AixQXEFqAeWSeIh1E5Uu8ML5U0NOUNU9w3s54OKBK
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
